// Sample data for MyBookmarks dashboard
// Categories (one per bookmark) + tags (multi)
// Mega cards: parent bookmark with children (no link on parent)
// Special features: searchable cards (search inside the destination site)

const CATEGORIES = [
  { id: 'iot',      name: 'IoT',           icon: '◉', hue: 28  },
  { id: 'media',    name: 'Media',         icon: '◐', hue: 280 },
  { id: 'hosting',  name: 'Hosting',       icon: '▣', hue: 200 },
  { id: 'devtools', name: 'Dev Tools',     icon: '◈', hue: 150 },
  { id: 'design',   name: 'Design',        icon: '◇', hue: 340 },
  { id: 'gaming',   name: 'Gaming',        icon: '◆', hue: 250 },
  { id: 'shopping', name: 'Shopping',      icon: '○', hue: 100 },
  { id: 'news',     name: 'News',          icon: '▤', hue: 10  },
  { id: 'home',     name: 'Home Admin',    icon: '⌂', hue: 50  },
  { id: 'docs',     name: 'Documentation', icon: '☷', hue: 220 },
];

// Each bookmark:
//   id, title, subtitle?, url?, category, tags[], color (hue 0-360),
//   logo (text initials or symbol), rating (0-5), favorite?
//   group? (parent id) -> child of mega card
//   isParent? -> mega card parent (no url)
//   search? { placeholder, urlTemplate (use {q}) }
//   logoStyle? optional override

const BOOKMARKS = [
  // ── IoT ─────────────────────────────────────────────────────
  { id: 'nginx', title: 'Nginx Proxy Manager', subtitle: 'nginxproxy.tonicastillo.com',
    url: 'https://nginxproxy.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'MacBookServer'], color: 32, logo: 'NPM', rating: 5 },
  { id: 'asus', title: 'ASUS Wireless Router', subtitle: 'router.tonicastillo.com',
    url: 'https://router.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'Network'], logo: 'ASUS', logoStyle: 'mono' },
  { id: 'tailscale', title: 'Tailscale Machines', subtitle: 'login.tailscale.com',
    url: 'https://login.tailscale.com/admin/machines', category: 'iot',
    tags: ['Servers', 'IoT'], color: 220, logo: '⋮⋮' },
  { id: 'unraid-elite', title: 'Elite — UNRAID', subtitle: 'elite.tonicastillo.com',
    url: 'https://elite.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'Servers'], color: 12, logo: 'R', rating: 5 },
  { id: 'unraid-fuji', title: 'Fuji — UNRAID', subtitle: 'fuji.tonicastillo.com',
    url: 'https://fuji.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'Servers'], color: 12, logo: 'R', rating: 5 },
  { id: 'unraid-api', title: 'Unraid API', subtitle: 'unraidapi.4d.es',
    url: 'https://unraidapi.4d.es', category: 'iot',
    tags: ['IoT', 'DevTools'], color: 18, logo: 'API' },
  { id: 'changedet', title: 'Change Detection', subtitle: 'changedetection.tonicastillo.com',
    url: 'https://changedetection.tonicastillo.com', category: 'iot',
    tags: ['IoT'], logo: '◯' },
  { id: 'jdownloader', title: 'JDownloader', subtitle: 'jdownloader.tonicastillo.com',
    url: 'https://jdownloader.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'Pirat'], logo: 'JD' },
  { id: 'nbn', title: 'NBN', subtitle: 'nbn.tonicastillo.com',
    url: 'https://nbn.tonicastillo.com', category: 'iot',
    tags: ['IoT'], logo: '⋄' },
  { id: 'transmission', title: 'Transmission', subtitle: 'transmission.tonicastillo.com',
    url: 'https://transmission.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'Pirat'], logo: 'T' },
  { id: 'nas-syn', title: 'NAS Synology', subtitle: 'nas.tonicastillo.com',
    url: 'https://nas.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'NAS'], logo: '▦' },
  { id: 'nas-files', title: 'NAS File Station', subtitle: 'nas.tonicastillo.com/files',
    url: 'https://nas.tonicastillo.com/files', category: 'iot',
    tags: ['IoT', 'NAS', 'Outside'], color: 42, logo: '▤' },
  { id: 'ha', title: 'HA Smart', subtitle: 'homeassistant.tonicastillo.com',
    url: 'https://homeassistant.tonicastillo.com', category: 'iot',
    tags: ['IoT', 'HomeAssistant'], color: 195, logo: '⌂' },
  { id: 'ring', title: 'Ring.com', subtitle: 'account.ring.com/dashboard',
    url: 'https://account.ring.com/account/dashboard', category: 'iot',
    tags: ['IoT'], logo: 'R' },
  { id: 'soulseek', title: 'SoulSeek (slsk)', subtitle: 'soulseek.tonicastillo.com',
    url: 'https://soulseek.tonicastillo.com', category: 'iot',
    tags: ['Music', 'Pirat', 'Home'], color: 195, logo: '✈', rating: 5 },

  // ── Media ───────────────────────────────────────────────────
  { id: 'navidrome', title: 'Navidrome', subtitle: 'music.tonicastillo.com',
    url: 'https://music.tonicastillo.com', category: 'media',
    tags: ['Music', 'Media'], color: 220, logo: '◉' },
  { id: 'jellyfin', title: 'Jellyfin', subtitle: 'home.tonicastillo.com',
    url: 'https://home.tonicastillo.com', category: 'media',
    tags: ['Media', 'Video'], color: 270, logo: '◬' },
  { id: 'comics', title: 'Comics', subtitle: 'comics.tonicastillo.com',
    url: 'https://comics.tonicastillo.com', category: 'media',
    tags: ['Comics', 'Media'], color: 35, logo: 'C!' },
  { id: 'zapi', title: 'Zapi TV', subtitle: 'ver.zapitv.com/webclient',
    url: 'https://ver.zapitv.com/webclient', category: 'media',
    tags: ['Media', 'Video'], color: 8, logo: 'Z' },
  { id: 'ebiblio', title: 'eBiblio Andalucía', subtitle: 'andalucia.cdn.eibiblio.es',
    url: 'https://andalucia.cdn.eibiblio.es', category: 'media',
    tags: ['Books', 'Media'], logo: 'eB' },

  // ── Mega card: Game Stores ──────────────────────────────────
  { id: 'gamestores', title: 'Game Stores', subtitle: 'PC game launchers & stores',
    isParent: true, category: 'gaming',
    tags: ['Gaming', 'Shopping'], color: 250, logo: '◆',
    search: { placeholder: 'Search across stores…', urlTemplate: 'https://www.google.com/search?q={q}+game+store' } },
  { id: 'steam', title: 'Steam', subtitle: 'store.steampowered.com',
    url: 'https://store.steampowered.com', category: 'gaming', group: 'gamestores',
    tags: ['Gaming'], color: 215, logo: 'S',
    search: { placeholder: 'Search Steam…', urlTemplate: 'https://store.steampowered.com/search/?term={q}' } },
  { id: 'epic', title: 'Epic Games', subtitle: 'store.epicgames.com',
    url: 'https://store.epicgames.com', category: 'gaming', group: 'gamestores',
    tags: ['Gaming'], color: 0, logo: 'E',
    search: { placeholder: 'Search Epic…', urlTemplate: 'https://store.epicgames.com/en-US/browse?q={q}' } },
  { id: 'gog', title: 'GOG', subtitle: 'gog.com',
    url: 'https://gog.com', category: 'gaming', group: 'gamestores',
    tags: ['Gaming'], logo: 'G' },
  { id: 'itch', title: 'itch.io', subtitle: 'itch.io',
    url: 'https://itch.io', category: 'gaming', group: 'gamestores',
    tags: ['Gaming', 'Inspiration'], color: 350, logo: 'i' },
  { id: 'humble', title: 'Humble Bundle', subtitle: 'humblebundle.com',
    url: 'https://humblebundle.com', category: 'gaming', group: 'gamestores',
    tags: ['Gaming', 'Shopping'], logo: 'H' },

  // ── Mega card: Dev Docs ─────────────────────────────────────
  { id: 'devdocs', title: 'Dev Docs', subtitle: 'Reference & docs',
    isParent: true, category: 'docs',
    tags: ['DevTools', 'Documentation'], color: 215, logo: '☷',
    search: { placeholder: 'Search all docs…', urlTemplate: 'https://devdocs.io/#q={q}' } },
  { id: 'mdn', title: 'MDN Web Docs', subtitle: 'developer.mozilla.org',
    url: 'https://developer.mozilla.org', category: 'docs', group: 'devdocs',
    tags: ['DevTools', 'Documentation'], color: 215, logo: 'M',
    search: { placeholder: 'Search MDN…', urlTemplate: 'https://developer.mozilla.org/en-US/search?q={q}' } },
  { id: 'react-docs', title: 'React', subtitle: 'react.dev',
    url: 'https://react.dev', category: 'docs', group: 'devdocs',
    tags: ['DevTools', 'ReactJS'], color: 195, logo: 'R',
    search: { placeholder: 'Search react.dev…', urlTemplate: 'https://react.dev/search?q={q}' } },
  { id: 'caniuse', title: 'Can I Use', subtitle: 'caniuse.com',
    url: 'https://caniuse.com', category: 'docs', group: 'devdocs',
    tags: ['DevTools', 'CSS'], logo: '?' },
  { id: 'devdocsio', title: 'DevDocs.io', subtitle: 'devdocs.io',
    url: 'https://devdocs.io', category: 'docs', group: 'devdocs',
    tags: ['DevTools', 'Documentation'], logo: 'd' },

  // ── Standalone Dev Tools ───────────────────────────────────
  { id: 'github', title: 'GitHub', subtitle: 'github.com',
    url: 'https://github.com', category: 'devtools',
    tags: ['DevTools', 'Git'], color: 280, logo: 'GH', favorite: true,
    search: { placeholder: 'Search GitHub…', urlTemplate: 'https://github.com/search?q={q}' } },
  { id: 'npm', title: 'npm', subtitle: 'npmjs.com',
    url: 'https://npmjs.com', category: 'devtools',
    tags: ['DevTools', 'npm'], color: 0, logo: 'N',
    search: { placeholder: 'Search packages…', urlTemplate: 'https://npmjs.com/search?q={q}' } },
  { id: 'stack', title: 'Stack Overflow', subtitle: 'stackoverflow.com',
    url: 'https://stackoverflow.com', category: 'devtools',
    tags: ['DevTools'], logo: 'S' },
  { id: 'codepen', title: 'CodePen', subtitle: 'codepen.io',
    url: 'https://codepen.io', category: 'devtools',
    tags: ['DevTools', 'CSS'], logo: '{ }' },
  { id: 'regex', title: 'RegExr', subtitle: 'regexr.com',
    url: 'https://regexr.com', category: 'devtools',
    tags: ['DevTools'], color: 195, logo: '/^/' },

  // ── Hosting ─────────────────────────────────────────────────
  { id: 'vercel', title: 'Vercel', subtitle: 'vercel.com/dashboard',
    url: 'https://vercel.com/dashboard', category: 'hosting',
    tags: ['Hosting', 'DevTools'], color: 0, logo: '▲', logoStyle: 'mono' },
  { id: 'cloudflare', title: 'Cloudflare', subtitle: 'dash.cloudflare.com',
    url: 'https://dash.cloudflare.com', category: 'hosting',
    tags: ['Hosting', 'CloudService'], color: 28, logo: '☁', favorite: true },
  { id: 'netlify', title: 'Netlify', subtitle: 'app.netlify.com',
    url: 'https://app.netlify.com', category: 'hosting',
    tags: ['Hosting'], logo: '◇' },
  { id: 'railway', title: 'Railway', subtitle: 'railway.app',
    url: 'https://railway.app', category: 'hosting',
    tags: ['Hosting', 'CloudService'], color: 280, logo: '⊥' },

  // ── Design ──────────────────────────────────────────────────
  { id: 'figma', title: 'Figma', subtitle: 'figma.com/files',
    url: 'https://figma.com/files', category: 'design',
    tags: ['Design', 'DesignTools'], color: 340, logo: 'F', favorite: true,
    search: { placeholder: 'Search Figma…', urlTemplate: 'https://figma.com/files?q={q}' } },
  { id: 'dribbble', title: 'Dribbble', subtitle: 'dribbble.com',
    url: 'https://dribbble.com', category: 'design',
    tags: ['Design', 'Inspiration'], color: 340, logo: '◍' },
  { id: 'pinterest', title: 'Pinterest', subtitle: 'pinterest.com',
    url: 'https://pinterest.com', category: 'design',
    tags: ['Design', 'Inspiration'], color: 8, logo: 'P',
    search: { placeholder: 'Search pins…', urlTemplate: 'https://pinterest.com/search/pins/?q={q}' } },
  { id: 'fonts', title: 'Google Fonts', subtitle: 'fonts.google.com',
    url: 'https://fonts.google.com', category: 'design',
    tags: ['Design', 'Typography'], color: 215, logo: 'Aa' },

  // ── Shopping ────────────────────────────────────────────────
  { id: 'amazon', title: 'Amazon', subtitle: 'amazon.es',
    url: 'https://amazon.es', category: 'shopping',
    tags: ['Shopping'], color: 32, logo: 'A',
    search: { placeholder: 'Search Amazon…', urlTemplate: 'https://amazon.es/s?k={q}' } },
  { id: 'aliexpress', title: 'AliExpress', subtitle: 'aliexpress.com',
    url: 'https://aliexpress.com', category: 'shopping',
    tags: ['Shopping'], logo: 'Ali' },
  { id: 'idealista', title: 'Idealista', subtitle: 'idealista.com',
    url: 'https://idealista.com', category: 'shopping',
    tags: ['Shopping', 'Appartment'], color: 145, logo: 'i' },

  // ── News ────────────────────────────────────────────────────
  { id: 'hn', title: 'Hacker News', subtitle: 'news.ycombinator.com',
    url: 'https://news.ycombinator.com', category: 'news',
    tags: ['News', 'DevTools'], color: 18, logo: 'Y', favorite: true },
  { id: 'verge', title: 'The Verge', subtitle: 'theverge.com',
    url: 'https://theverge.com', category: 'news',
    tags: ['News'], logo: 'V' },
  { id: 'rss', title: 'FreshRSS', subtitle: 'rss.tonicastillo.com',
    url: 'https://rss.tonicastillo.com', category: 'news',
    tags: ['News', 'Home'], logo: '⏵' },

  // ── Home Admin ──────────────────────────────────────────────
  { id: 'gas', title: 'Endesa', subtitle: 'endesaclientes.com',
    url: 'https://endesaclientes.com', category: 'home',
    tags: ['Home', 'HomeAdmin'], color: 215, logo: 'E' },
  { id: 'bank', title: 'BBVA', subtitle: 'bbva.es',
    url: 'https://bbva.es', category: 'home',
    tags: ['Home', 'HomeAdmin'], color: 220, logo: 'B' },
  { id: 'movistar', title: 'Movistar', subtitle: 'movistar.es',
    url: 'https://movistar.es', category: 'home',
    tags: ['Home', 'HomeAdmin'], logo: 'M' },
];

window.CATEGORIES = CATEGORIES;
window.BOOKMARKS = BOOKMARKS;
